version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: air-mongo
    volumes:
      - air-data:/data/db
    networks:
      - airsense
    ports:
      - 27017:27017

networks:
  airsense:
    name: air-network
    driver: bridge

volumes:
  air-data:
    name: air-data
